import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default [
	{
		input: "src/request.dev.js",
		output: {
			file: "dist/tmdb_proxy_request.dev.js",
			format: "es",
			banner: `/* TMDB Proxy Request Script (Dev) - Generated by Rollup */\n/* Build Date: ${new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} */`,
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()],
	},
	{
		input: "src/response.dev.js",
		output: {
			file: "dist/tmdb_proxy_response.dev.js",
			format: "es",
			banner: `/* TMDB Proxy Response Script (Dev) - Generated by Rollup */\n/* Build Date: ${new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} */`,
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs()],
	},
];
