import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default [
	{
		input: "src/request.js",
		output: {
			file: "dist/tmdb_proxy_request.js",
			format: "iife",
			banner: `/* TMDB Proxy Request Script - Generated by Rollup */\n/* Build Date: ${new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} */`,
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()],
	},
	{
		input: "src/response.js",
		output: {
			file: "dist/tmdb_proxy_response.js",
			format: "iife",
			banner: `/* TMDB Proxy Response Script - Generated by Rollup */\n/* Build Date: ${new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} */`,
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()],
	},
	{
		input: "src/Hono.js",
		output: {
			file: "dist/api.mjs",
			format: "esm",
			banner: `/* TMDB Proxy API - Generated by Rollup */\n/* Build Date: ${new Date().toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} */`,
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"], preferBuiltins: true }), commonjs(), terser()],
	},
];
